# Generated by Django 3.1.3 on 2021-07-31 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.fields.status
import utils.fields.timestamp
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('header', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
