# Generated by Django 3.1.3 on 2021-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_remove_interaction_timestampe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='content',
            field=models.TextField(),
        ),
    ]
