# Generated by Django 3.1.3 on 2021-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_auto_20210720_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='header',
            field=models.TextField(),
        ),
    ]
